<p>Login</p>
<textarea id="a" rows="10" cols="60"></textarea>
<script type="text/javascript">
	
	var token = "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6IjhlMTk1M2RiM2QxODJmNGRmM2NkMTkzZThhMGQyZjc0OTY1ZWI2ZmNlZTIyYTc4ZmZmNDUzNjdiYTExZTVjY2VhNzA5MWJlODZjYjhiOTk1In0.eyJhdWQiOiIxIiwianRpIjoiOGUxOTUzZGIzZDE4MmY0ZGYzY2QxOTNlOGEwZDJmNzQ5NjVlYjZmY2VlMjJhNzhmZmY0NTM2N2JhMTFlNWNjZWE3MDkxYmU4NmNiOGI5OTUiLCJpYXQiOjE1MTM5MDE2MDMsIm5iZiI6MTUxMzkwMTYwMywiZXhwIjoxNTEzOTA1MjAzLCJzdWIiOiIxIiwic2NvcGVzIjpbIltcInRlc3RcIl0iXX0.VWHZz3ZS88gh26BINPteU17LH8WhiWUc6Kum1T9v_nvC_ZXL_N3eGKeQZm9nZhTA_YUVQCsfNy1_gKVnX0dU6kYdY9s3zVhpXOIDJrhK2se1SFoDybtO2olr56EowUjk3vdSjufi8hR5gGmdVQvSjN7BavOEKYfywo_VImfORi8";
	var xhr = new XMLHttpRequest();
	var fd = new FormData();
	//fd.append('Authorization', token);
	xhr.onload = () => {
		if (xhr.status === 200) {
			var data = xhr.response;
			document.getElementById('a').value = data;
		} else {
			xhr.onerror();
		}
	}
	xhr.onerror = () => {
		var data = xhr.response;
		document.getElementById('a').value = data;
	}
	xhr.open('GET', 'test');
	xhr.setRequestHeader('Authorization', token);
	xhr.send(fd);
</script>